// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PZ_Projekt.Data;

#nullable disable

namespace PZ_Projekt.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240607134022_seeder4")]
    partial class seeder4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PZ_Projekt.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("PZ_Projekt.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ItemId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("PZ_Projekt.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 28,
                            Category = "GPU",
                            Description = "Szukasz uniwersalnej karty graficznej w przystępnej cenie, która wykazywać się będzie wysokim standardem? MSI GeForce RTX 4070 Ti Ventus 2X 12G jest bardzo przyzwoitą opcją, która spełni oczekiwania praktycznie każdego użytkownika – niezależnie od tego, czy Twój PC ma służyć do profesjonalnego grania, pracy, czy też do tworzenia kreatywnych projektów.",
                            ImageUrl = "/uploads/503414e8-2efb-4cbb-8e1c-fcca2bd46612.jpg",
                            Name = "Karta graficzna MSI GeForce RTX 4070",
                            Price = 3300m
                        },
                        new
                        {
                            Id = 29,
                            Category = "GPU",
                            Description = "Wciąż poszukujesz karty graficznej, która nie zawiedzie Cię, bez względu na to, czego będziesz od niej oczekiwał? Pora zapoznać się z prawdziwym tytanem wydajności, który przeniesie Cię do świata bezkompromisowych osiągów. Gigabyte GeForce RTX 4060 EAGLE OC 8G to układ graficzny, którego możliwości wprawią Cię osłupienie. Grafika generowana grach jeszcze nigdy nie była tak realistyczna, a zadanie związane z koniecznością wykonania skomplikowanych obliczeń – tak szybko wykonane. Sprawdź i przekonaj się na własnej skórze.",
                            ImageUrl = "/uploads/0ccbc04e-2d4a-447b-be7b-17eea24c4722.jpg",
                            Name = "Karta graficzna Gigabyte GeForce RTX 4060 Eagle OC 8GB GDDR6",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 30,
                            Category = "GPU",
                            Description = "Daj się zaskoczyć karcie graficznej MSI GeForce RTX 3060 VENTUS, której procesor graficzny zapewni Ci wydajność, o jakiej marzyłeś. Model z serii GeForce 30 w porównaniu z egzemplarzami poprzedniej serii (GeForce 20) charakteryzują o wiele większe zaawansowanie technologiczne i imponująca ilość funkcji. Karta posiada 12 GB najszybszej dostępnej pamięci GDDR6, pozwalającej na obsługę nawet bardzo wymagających zadań",
                            ImageUrl = "/uploads/1119750d-42b6-4f4b-9a43-c70b6a780eb4.jpg",
                            Name = "Karta graficzna MSI GeForce RTX 3060 Ventus 2X OC 12GB GDDR6",
                            Price = 1300m
                        },
                        new
                        {
                            Id = 31,
                            Category = "CPU",
                            Description = "Dwunasta generacja procesorów Intel Core dla komputerów stacjonarnych - Alder Lake, opracowana została przede wszystkim po to, by sprostać wymaganiom graczy, oczekujących od zestawów komputerowych niezrównanej wydajności zarówno w rozrywce, jak i pracy wielozadaniowej.  Dwa rodzaje rdzeni procesora Intel Core i5-12400F zadbają o to, by wydajności nie zabrakło nawet w najbardziej wymagających produkcjach. Łącznie procesor wyposażony został w aż 6 rdzeni i 12 wątków.",
                            ImageUrl = "/uploads/7e0dc800-3893-4e7f-8708-078087cc65bb.jpg",
                            Name = "Procesor Intel Core i5-12400F, 2.5 GHz, 18 MB, BOX",
                            Price = 489m
                        },
                        new
                        {
                            Id = 32,
                            Category = "CPU",
                            Description = "Od grupowych starć do niezapomnianych przygód — zanurz się w środek akcji jak nigdy dotąd! Wszystko to zapewni Ci najnowocześniejszy procesor Intel Core i7-14700k. Osiąga on prędkość do 5.6 GHz i posiada 8 rdzeni wysokiej wydajności oraz 12 rdzeni energooszczędnych. Ten zaawansowany procesor Intel Core i7 nowej generacji jest również gotowy do tuningu. Podkręć swoje gry, nie martwiąc się o procesy w tle obciążające system.",
                            ImageUrl = "/uploads/7c38da4a-698f-4b64-a10d-63ec5d216a46.jpg",
                            Name = "Procesor Intel Core i7-14700K, 3.4 GHz, 33 MB, BOX",
                            Price = 1779m
                        },
                        new
                        {
                            Id = 33,
                            Category = "CPU",
                            Description = "AMD Ryzen 5 5600 to procesor stanowiący odpowiedź producenta na potrzeby wszystkich tych, którzy szukają wydajnego układu do komputerów dla graczy i stanowisk pracy profesjonalistów. Wysoka wydajność gwarantowana przez najnowszą architekturę - AMD Zen 3, to jego największy atut.",
                            ImageUrl = "/uploads/1c89fa01-b4b4-4fc1-9761-6c4ce35c4c1c.jpg",
                            Name = "Procesor AMD Ryzen 5 5600, 3.5 GHz, 32 MB, BOX",
                            Price = 519m
                        },
                        new
                        {
                            Id = 34,
                            Category = "RAM",
                            Description = "Pamięć Lexar® THOR DDR4 UDIMM do komputerów stacjonarnych zwiększa wydajność komputera dzięki pamięci DDR4 i jest przeznaczona dla entuzjastów komputerów PC i ekstremalnych graczy. Charakteryzuje się wysoką wydajnością pamięci DDR4 i kosmicznym aluminiowym radiatorem zapewniającym doskonałe wykończenie i wysoce wydajne odprowadzanie ciepła, aby system działał w niskiej temperaturze.",
                            ImageUrl = "/uploads/d75c3c10-c765-4a05-ae7c-09ead448ef73.jpg",
                            Name = "Pamięć Lexar Thor, DDR4, 32 GB, 3600MHz, CL18",
                            Price = 299m
                        },
                        new
                        {
                            Id = 35,
                            Category = "RAM",
                            Description = "Pamięć Kingston FURY™ Beast DDR4 o częstotliwości taktowania do 3733MHz to potężny ładunek wydajności w grach, edycji materiałów wideo i renderowaniu grafiki. Pamięć o częstotliwości taktowania od 2666MHz do 3733MHz i opóźnieniu od CL15 do CL19 to niedrogi sposób na modernizację komputera. Pojemność pojedynczego modułu wynosi od 4GB do 32GB, a pojemność zestawów od 8GB do 128GB. Pamięć jest wyposażona w funkcję automatycznego przetaktowania Plug N Play do częstotliwości 2666MHz, a także zgodna z technologią Intel XMP i procesorami AMD Ryzen. Chłodzenie pamięci FURY Beast DDR4 zapewnia stylowy, niskoprofilowy radiator. Każdy moduł pamięci przechodzi testy przy pełnej szybkości i jest objęty wieczystą gwarancją. To bezproblemowe i przystępne cenowo rozwiązanie przeznaczone do modernizacji systemu z procesorem Intel lub AMD.",
                            ImageUrl = "/uploads/54f6eaf6-3d98-4bab-8b2f-9e229f4bce1d.jpg",
                            Name = "Pamięć Kingston Fury Beast, DDR4, 16 GB, 3200MHz, CL16",
                            Price = 199m
                        },
                        new
                        {
                            Id = 36,
                            Category = "RAM",
                            Description = "Seria pamięci Viper Venom DDR5 jest najszybszą dostępną pamięcią firmy Patriot  dla najnowszych platform DDR5, zapewniając gracom szaloną wydajność systemu! Moduły pamięci Viper Venom DDR5 zostały zaprojektowane w oparciu o przełomową technologię, aby wyznaczać standardy wyższe niż większość ekstremalnie przetaktowanych modułów DDR4 oraz zapewniać dwukrotnie większą szybkość, podwajając obecną przepustowość DDR4.",
                            ImageUrl = "/uploads/8a259862-04cc-4fe8-a2a3-978181492897.jpg",
                            Name = "Pamięć Patriot Viper Venom, DDR5, 32 GB, 6000MHz, CL36",
                            Price = 459m
                        },
                        new
                        {
                            Id = 37,
                            Category = "zasilacze",
                            Description = "Endorfy Supremo FM5 Gold 850 W jest wydajnym zasilaczem, który spokojnie udźwignie wyśrubowane wymagania podzespołów Twojego peceta. Przygotuj się na wsparcie z najwyższej półki – bez niespodziewanych resetów.",
                            ImageUrl = "/uploads/5dfb79fe-d215-4e97-a3b8-65325cfd45d4.jpg",
                            Name = "Zasilacz Endorfy Supremo FM5 Gold 850W",
                            Price = 599m
                        },
                        new
                        {
                            Id = 38,
                            Category = "zasilacze",
                            Description = "Kondensatory główne pochodzą od najwyższej klasy japońskich producentów, zapewniając wysokiej jakości i stabilne zasilanie, które skutecznie wydłuża żywotność produktu.",
                            ImageUrl = "/uploads/868ca153-7add-4457-91fb-808ad6f60662.jpg",
                            Name = "Zasilacz Gigabyte P650G 650W",
                            Price = 252m
                        },
                        new
                        {
                            Id = 39,
                            Category = "zasilacze",
                            Description = "Innowacyjny, zgłoszony do opatentowania boczny panel zasilacza z modułowymi złączami umożliwia wygodne podłączanie przewodów z boku. Dzięki temu kable można porządkować i podłączać łatwiej niż kiedykolwiek przedtem.",
                            ImageUrl = "/uploads/c0e4f85d-5cdf-4823-9af7-69abd8a3d575.jpg",
                            Name = "Zasilacz Corsair RM850x SHIFT 850W",
                            Price = 705m
                        },
                        new
                        {
                            Id = 40,
                            Category = "dysk",
                            Description = "Model 990 EVO oferuje większe prędkości odczytu i zapisu sekwencyjnego (do 5 000 i 4 200 MB/s) oraz losowego (do 700 i 800 K IOPS), czyli o 43% więcej niż w 970 EVO Plus 2TB. Krótszy czas oczekiwania na gry i szybki dostęp do dużych plików.",
                            ImageUrl = "/uploads/ac1384bd-bd91-4d8a-b5fd-7371603b1176.jpg",
                            Name = "Dysk SSD Samsung 990 EVO 1TB M.2 2280 PCI-E x4 Gen4 NVMe",
                            Price = 632m
                        },
                        new
                        {
                            Id = 41,
                            Category = "dysk",
                            Description = "Dyski SSD o formacie 2,5 cala to niewielkie i lekkie sprzęty często instalowane w laptopach. Znalazły również zastosowanie, jako urządzenia zewnętrzne. To pierwszy format dysków SSD, który nadal cieszy się ogromną popularnością. Do największych zalet można zaliczyć kompaktowe rozmiary i prosty montaż w obudowach. Bardzo atrakcyjna oferta pozwoli na wybór sprzętu różnych producentów. Szeroki zakres parametrów technicznych pozwoli idealnie dobrać dysk do osobistych preferencji i oczekiwanych funkcji.",
                            ImageUrl = "/uploads/f791c5ed-c21e-4066-aea9-78086d5c13b8.jpg",
                            Name = "Dysk SSD Gigabyte 256GB 2.5\" SATA III",
                            Price = 100m
                        },
                        new
                        {
                            Id = 42,
                            Category = "dysk",
                            Description = "Dzięki pamięci Flash NAND 3D NAND dysk SU650 zapewnia większą wydajność i lepszą niezawodność w porównaniu do dysków SSD NAND 2D z lepszym stosunkiem ceny do wydajności.",
                            ImageUrl = "/uploads/c9dd6451-cc80-4146-b7b5-1bf02c3316dc.jpg",
                            Name = "Dysk SSD ADATA Ultimate SU650 1TB 2.5\" SATA III",
                            Price = 250m
                        },
                        new
                        {
                            Id = 43,
                            Category = "chłodzenie",
                            Description = "Fera 5 Black bez problemu utrzymuje niską temperaturę procesora nawet wtedy, kiedy komputer pracuje na najwyższych obrotach. To zasługa asymetrycznego radiatora z gęstym użebrowaniem, który dobrze zbiera energię cieplną – jego podstawa dokładnie styka się z powierzchnią procesora, a cztery ciepłowody poprawiają odbieranie wysokich temperatur. Cooler jest też zoptymalizowany do jednokierunkowego przepływu powietrza, co zapewnia najlepszą w swojej klasie wydajność chłodzenia.",
                            ImageUrl = "/uploads/20271e79-9c9d-4a8e-a7ce-d2fd488f901a.jpg",
                            Name = "Chłodzenie CPU Endorfy Fera 5 Black",
                            Price = 149m
                        },
                        new
                        {
                            Id = 44,
                            Category = "chłodzenie",
                            Description = "Dark Rock Pro 5 posiada 7 wysokowydajnych miedzianych rurek cieplnych oraz specjalną czarną powłokę z cząsteczkami ceramicznymi. Dzięki temu ten wysokiej klasy cooler utrzymuje procesor w najwyższej wydajności przez cały czas, nawet w mocno podkręconych systemach i wymagających stacjach roboczych.",
                            ImageUrl = "/uploads/0fc6b1c7-afff-4887-ac36-1cfd4966006e.jpg",
                            Name = "Chłodzenie CPU be quiet! Dark Rock Pro 5",
                            Price = 367m
                        },
                        new
                        {
                            Id = 45,
                            Category = "chłodzenie",
                            Description = "Nadeszła era cyfrowych chłodzeń powietrza, a DeepCool z dumą przedstawia AK620 Digital. Wszystko, co kochałeś w AK620 Zero Dark, ale z eleganckim niskoprofilowym magnetycznym wyświetlaczem statusu i paskami LED ARGB.",
                            ImageUrl = "/uploads/54b35329-7d38-4e8b-93e2-9926926cc020.jpg",
                            Name = "Chłodzenie CPU Deepcool AK620 Digital",
                            Price = 299m
                        });
                });

            modelBuilder.Entity("PZ_Projekt.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("PZ_Projekt.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PZ_Projekt.Models.CartItem", b =>
                {
                    b.HasOne("PZ_Projekt.Models.Cart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("PZ_Projekt.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("PZ_Projekt.Models.OrderItem", b =>
                {
                    b.HasOne("PZ_Projekt.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PZ_Projekt.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PZ_Projekt.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("PZ_Projekt.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
